Feature/프로젝트 생성 페이지
wafflestudio/guam_front pull request #17
Opened 2021-05-30 03:37 UTC by YeonghyeonKO

> resolves #12 #5 

- `Back()`을 수행하면 기존 데이터가 남아 있는 것처럼 이전 페이지로 왔다가 `다음`을 눌러 다시 다음 페이지로 가면 데이터가 남아 있어야 합니다. 일단은 생성 페이지1의 경우 _saveTitle와 같은 함수들을 통해 User의 입력값을 input 딕셔너리에 저장했는데, 이를 계속 보관했다가 렌더링하는 방식은 별로라고 생각합니다. 어떻게 하면 context를 유지하면서 데이터 보관 문제를 해결할 수 있을까요?

<img width="325" alt="image" src="https://user-images.githubusercontent.com/46114393/120091080-94992980-c142-11eb-8369-12b108280513.png">

<img width="332" alt="image" src="https://user-images.githubusercontent.com/46114393/120091088-a8dd2680-c142-11eb-8353-aab48ed4575a.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/46114393/120091096-babec980-c142-11eb-9dda-128995a04979.png">

2021-05-31 06:54 UTC, gajagajago commented
앗 네 !! 제가 지금 셤이 넘 많아서 .. review 가능할 때 해놓겠습니다 ㅠㅠ

2021-05-31 09:13 UTC, YeonghyeonKO commented
@gajagajago 천천히 하셔도 됩니다!! 저도 이제부터 시험기간 시작인지라 ㅎㅎ..

2021-06-19 08:30 UTC, gajagajago commented
다음 클릭 시 아예 앱바까지 새로운 페이지가 위에 스택 되는데, 페이지 내용만 바뀌고 페이지가 위에 쌓이지 않게 할 수 없을까요? 즉 Next Page를 통해서 페이지 간 '이동' 이 되는 것이 아니라, creation page의 content만 바뀌는 형태로요. 

  1. 각 페이지에서 채워지는 Map을 갖고 있는 글로벌한 create page.  
  2. 그 안에서 page index에 따라 렌더링 될 세부 페이지들.  
  3. 다음 / (이전 버튼.. if necessary) 을 통한 페이지 인덱싱 및 페이지에서 요구하는 필드가 모두 채워 져야만 다음 버튼 활성화
4. 마지막 페이지에선 글로벌한 create page의 Map을 서버로 request.   가 가능해야 할 것 같습니다.

2021-06-19 08:33 UTC, gajagajago requested changes

2021-06-19 08:33 UTC, gajagajago commented on lib/commons/next_page.dart
> +  final Map data;
data field는 사용되고 있지 않는데, 이전 페이지의 Map data를 계속 다음 페이지로 넘겨주기 위한 필드인가요?

2021-06-19 08:33 UTC, gajagajago commented on lib/screens/projects/creation/project_create_body_1.dart
> +              setState(() {
위에 함수 선언을 보면 이미 setState 하는 함수로 선언되어 있는데 또 setState() 함수 안에 넣을 필요가 있을까요?

2021-06-19 08:33 UTC, gajagajago commented on lib/screens/projects/creation/project_create_body_1.dart
> +              setState(() {
// 여기도..

2021-06-19 08:33 UTC, gajagajago commented on lib/screens/projects/creation/project_create_body_1.dart
> +                              setState(() => _value = selected ? e.key : null);
// 여기도..

2021-06-22 15:35 UTC, gajagajago approved these changes

2021-06-22 15:44 UTC, merged