Boards 디자인 및 기능 완성
wafflestudio/guam_front pull request #24
Opened 2021-06-24 09:27 UTC by gajagajago

작업실 기능이 어느정도 완성되었습니다!

2021-06-24 15:13 UTC, YeonghyeonKO requested changes
`Icon(task_outlined)` 관련된 comment 아니면 critical한 comment는 없습니다! 제 개발환경에서만 안뜨는건지 의문이네요...

2021-06-24 15:13 UTC, YeonghyeonKO commented on lib/screens/boards/thread_page.dart
> +                DateFormat("M월 d일 hh:mm").format(thread.createdAt).toString(),
크게 중요한건 아닌데, year는 들어가야할 것 같습니다! (만약 며칠전 등의 로직까지 구현하지 않는다면 속편하게)

2021-06-24 15:26 UTC, YeonghyeonKO commented
당장 급한 문제는 아니지만 생각해보니 만약 프로젝트 이름 및 프로젝트원 닉네임을 모두 가나다순으로 나열한다고 한다면, 성민님 디자인대로 구현이 가능할 것 같기도 하네요. 

1. (작업실의 경우) 색은 가나다순에 따라 지정되어 있어서 가나다 순에 따라 상단 프로젝트별 작업실 표시가 바뀜.
<img width="623" alt="image" src="https://user-images.githubusercontent.com/46114393/123289328-575e6680-d54b-11eb-99cf-91e479f52812.png">

<br>

2. (작업 현황의 경우) 색을 고려할 필요가 없으니 가나다순으로 (n)번째 profile image를 클릭할 때마다 (n-1)번째까지의 profile image가 왼쪽으로 이동함.
<img width="602" alt="image" src="https://user-images.githubusercontent.com/46114393/123289526-8248ba80-d54b-11eb-9b2c-992b18b914e0.png">

2021-06-24 15:27 UTC, YeonghyeonKO commented
참고로 `제2의 GUAM 만들기` 작업실은 죽어버렸네요 흑흑

![Screenshot_1624548053](https://user-images.githubusercontent.com/46114393/123290240-1155d280-d54c-11eb-85b3-a8998dda53df.png)

2021-06-25 04:02 UTC, gajagajago commented on lib/screens/boards/thread_page.dart
> +                DateFormat("M월 d일 hh:mm").format(thread.createdAt).toString(),
`며칠 전` 로직 만들겠습니다 ! (일단 뷰 부터 다 만들고 만들겠습니닷,,)

2021-06-25 04:02 UTC, gajagajago commented
> 참고로 `제2의 GUAM 만들기` 작업실은 죽어버렸네요 흑흑
> 
> ![Screenshot_1624548053](https://user-images.githubusercontent.com/46114393/123290240-1155d280-d54c-11eb-85b3-a8998dda53df.png)

ㅋㅋㅋㅋ element를 버려서 그렇습니다.

2021-06-25 04:03 UTC, gajagajago commented on lib/screens/boards/progresses.dart
> +          iconTitle(icon: Icons.task_outlined, title: "작업 현황"),
딴 걸로 바꾸겠습니다 !

2021-06-25 04:04 UTC, gajagajago commented
작업실 헤더랑 Progress 바 다시 작업해보겠습니다.

2021-06-25 12:58 UTC, merged