프로필 탭 디자인
wafflestudio/guam_front pull request #33
Opened 2021-07-06 14:36 UTC by YeonghyeonKO

- 배경, GitHub 로고를 제외하고는 디자인 완성하였습니다.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/46114393/124618594-e146f180-deb2-11eb-85b6-5b6b2c7a031e.png">

2021-07-07 16:00 UTC, gajagajago requested changes
+ image 업로드 시 동그란 기본 컨테이너 '안'에 딱 들어가게 부탁드립니다. 현재는 네모난 모양으로 튀어나오네요!!

2021-07-07 16:00 UTC, gajagajago commented on lib/screens/my_page/make_profile_page.dart
> +        value: (v) => []);
굳이 모든 stack item을 돌면서 postion 값을 넣기보단, 그냥 techStacks = {'FRONTEND': [], 'BACKEND': [], 'DESIGNER': []} 로 생성하는 게 낫지 않을까요? 유지 보수가 자주 필요할 부분은 아닌 거 같기 때문입니다.

2021-07-07 16:00 UTC, gajagajago commented on lib/screens/my_page/make_profile_page.dart
> +        }));
여기도 그냥 forEach문 쓰는 게 깔끔할 것 같습니다! 
stackProvider.stacks.forEach((e) => techStacks[e.position].add(e.name))

2021-07-07 16:00 UTC, gajagajago commented on lib/screens/my_page/make_profile_page.dart
> +        (key) => {techStacks[key] = List<String>.from(techStacks[key])});
여기는 어떤 일을 하는 부분인가요?

2021-07-07 16:00 UTC, gajagajago commented on lib/screens/my_page/make_profile_page.dart
> +    techStacks.remove('DESIGNER');
hashMap의 remove 함수의 return이 remove 된 객체이기 때문에, 아래 syntax로 써주시면 좋습니다 ! 
hashMap.put("New_Key", hashMap.remove("Old_Key"));

2021-07-07 16:00 UTC, gajagajago commented on lib/screens/my_page/profile_filter_value_chip.dart
> +  final List<String> reportList;
.dart 파일 명은 해당 파일의 main class 이름과 맞춰주시길... ( small rule )

2021-07-08 06:29 UTC, YeonghyeonKO commented on lib/screens/my_page/make_profile_page.dart
> +        value: (v) => []);
@gajagajago 맞아요 그 부분에서 고민하다가 결국 현재 코드대로 갔는데 어차피 F, B, D key 값 자체의 수정이 자주 일어나지 않는다는 가정 하에서 `techStacks = {'FRONTEND': [], 'BACKEND': [], 'DESIGNER': []}`로 가겠습니다!

2021-07-08 06:31 UTC, YeonghyeonKO commented
@gajagajago `SHIFT + CMD + L` 단축키로 매번 재정렬하는데, 들여쓰기가 이상할 때가 있더라구요 어떻게 정렬하신건가요?

2021-07-09 05:39 UTC, YeonghyeonKO commented on lib/screens/my_page/profile_filter_value_chip.dart
> +  TechStacksMultiSelectChip(this.reportList, {this.onSelectionChanged});
함수명이라서 그렇게하였는데 사실 빼는게 더 깔끔하겠네요 ㅎㅎ

2021-07-09 09:53 UTC, YeonghyeonKO commented on lib/screens/my_page/make_profile_page.dart
> +    techStacks.remove('DESIGNER');
오 그렇군요... put method가 없는 것 같아 `techStacks['백엔드'] = techStacks.remove('BACKEND');` 이렇게 처리해버렸습니다!

2021-07-09 11:37 UTC, gajagajago approved these changes

2021-07-09 11:55 UTC, merged